import http from 'http';
import url from 'url';
import cron from 'node-cron';
import { db, collection, addDoc, updateDoc, doc, query, where, getDocs, serverTimestamp } from './firebaseBackend.js';
import { getRandomLeetCodeChallenge } from './leetcodeScraper.js';
import { generate10Testcases, cleanHtml } from './testcaseGenerator.js';
import { buildWeeklyChallengePayload } from './automateChallenge.js';

/**
 * ╔══════════════════════════════════════════════════════════════════════════════════╗
 * ║                  TECHSPARK UNIFIED BACKEND & SCHEDULER SERVER                    ║
 * ║  Timezone: Asia/Kolkata (IST - Indian Standard Time)                             ║
 * ║                                                                                  ║
 * ║  🔥 Port 8008: HTTP API & MCP Challenge Generator                                ║
 * ║  📅 Friday 20:00 (8:00 PM IST): Auto-fetch & Schedule if not already posted       ║
 * ║  ⚡ Saturday 00:00 (Midnight IST): Auto-Go LIVE for students                      ║
 * ║  🔒 Sunday 23:59 (11:59 PM IST): Auto-Close weekly challenge                     ║
 * ║  ⏱️ 1-Minute Continuous Sync: Real-time transition heartbeat                      ║
 * ╚══════════════════════════════════════════════════════════════════════════════════╝
 */

const PORT = process.env.PORT || 8008;

// ═══════════════════════════════════════════════════════════
//  HELPER FUNCTIONS & SCHEDULER LOGIC
// ═══════════════════════════════════════════════════════════

function parseISTDate(dateInput) {
    if (!dateInput) return null;
    if (typeof dateInput === 'object' && dateInput.toMillis) {
        return new Date(dateInput.toMillis());
    }
    if (typeof dateInput === 'number') {
        return new Date(dateInput);
    }
    if (typeof dateInput === 'string') {
        const str = dateInput.trim();
        if (str.includes('+') || str.endsWith('Z')) {
            return new Date(str);
        }
        if (/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}(:\d{2})?$/.test(str)) {
            return new Date(str.replace(' ', 'T') + '+05:30');
        }
        return new Date(str);
    }
    return new Date(dateInput);
}

async function getExistingWeekendChallenge() {
    try {
        const qScheduled = query(collection(db, "ts_challenges"), where("status", "==", "scheduled"));
        const qActive = query(collection(db, "ts_challenges"), where("status", "==", "active"));

        const [scheduledSnap, activeSnap] = await Promise.all([
            getDocs(qScheduled),
            getDocs(qActive)
        ]);

        if (!activeSnap.empty) return activeSnap.docs[0];
        if (!scheduledSnap.empty) return scheduledSnap.docs[0];
        return null;
    } catch (err) {
        console.error("❌ [SERVER] Error checking existing challenges:", err.message);
        return null;
    }
}

/**
 * 1. Friday 20:00 (8:00 PM IST): Auto-fetch & Schedule if not already posted
 */
export async function triggerFridayEveningSchedule() {
    console.log("\n⏰ [SCHEDULER] Friday 20:00 IST — Checking for weekend challenge...");
    try {
        const existing = await getExistingWeekendChallenge();
        if (existing) {
            console.log(`   ℹ️ Challenge already exists: "${existing.data().title}" (${existing.id}) [${existing.data().status}]`);
            return existing.data();
        }

        console.log("   🚀 No challenge found. Auto-generating fresh LeetCode challenge...");
        const weekNumber = Math.ceil(new Date().getDate() / 7);
        const difficulty = weekNumber % 2 === 0 ? "MEDIUM" : "EASY";

        const payload = await buildWeeklyChallengePayload(difficulty);
        if (!payload) {
            console.error("❌ [SCHEDULER] Failed to generate challenge payload.");
            return null;
        }

        payload.status = "scheduled";

        const docRef = await addDoc(collection(db, "ts_challenges"), {
            ...payload,
            autoGenerated: true,
            createdAt: serverTimestamp()
        });

        console.log(`✅ [SCHEDULER] Friday 20:00 IST — Challenge scheduled for Saturday 00:00 IST!`);
        console.log(`   📝 Title: ${payload.title} | 🎯 Difficulty: ${payload.difficulty} | ⏳ ID: ${docRef.id}`);
        return { id: docRef.id, ...payload };
    } catch (err) {
        console.error("❌ [SCHEDULER] Error in Friday schedule:", err.message);
        return null;
    }
}

/**
 * 2. Saturday 00:00 IST: Auto-Go LIVE
 */
export async function triggerSaturdayLiveActivation() {
    console.log("\n⚡ [SCHEDULER] Saturday 00:00 IST — Promoting challenge to LIVE...");
    try {
        const q = query(collection(db, "ts_challenges"), where("status", "==", "scheduled"));
        const snapshot = await getDocs(q);

        if (!snapshot.empty) {
            for (const docSnap of snapshot.docs) {
                await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                    status: "active",
                    activatedAt: serverTimestamp()
                });
                console.log(`   ⚡ [LIVE] Activated scheduled challenge: "${docSnap.data().title}" (${docSnap.id})`);
            }
            return { activatedCount: snapshot.docs.length };
        }

        // If no challenge was scheduled, generate and activate immediately
        console.log("   🚀 No scheduled challenge found. Creating live challenge immediately...");
        const weekNumber = Math.ceil(new Date().getDate() / 7);
        const difficulty = weekNumber % 2 === 0 ? "MEDIUM" : "EASY";
        const payload = await buildWeeklyChallengePayload(difficulty);
        if (payload) {
            payload.status = "active";
            const docRef = await addDoc(collection(db, "ts_challenges"), {
                ...payload,
                autoGenerated: true,
                createdAt: serverTimestamp()
            });
            console.log(`   ✅ [LIVE] Published and activated: "${payload.title}" (${docRef.id})`);
            return { id: docRef.id, ...payload };
        }
    } catch (err) {
        console.error("❌ [SCHEDULER] Error in Saturday activation:", err.message);
    }
    return null;
}

/**
 * 3. Sunday 23:59:59 IST: Auto-Close
 */
export async function triggerSundayClose() {
    console.log("\n🔒 [SCHEDULER] Sunday 23:59 IST — Ending & closing active challenge...");
    try {
        const q = query(collection(db, "ts_challenges"), where("status", "==", "active"));
        const snapshot = await getDocs(q);

        if (snapshot.empty) {
            console.log("   ℹ️ No active challenges to close.");
            return { closedCount: 0 };
        }

        for (const docSnap of snapshot.docs) {
            await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                status: "closed",
                closedAt: serverTimestamp()
            });
            console.log(`   🔒 [CLOSED] Closed challenge: "${docSnap.data().title}" (${docSnap.id})`);
        }
        return { closedCount: snapshot.docs.length };
    } catch (err) {
        console.error("❌ [SCHEDULER] Error closing Sunday challenge:", err.message);
        return null;
    }
}

/**
 * 4. Real-time 1-Minute Synchronization Heartbeat
 */
export async function checkRealtimeSync() {
    try {
        const now = Date.now();

        // 1. Promote scheduled -> active
        const qScheduled = query(collection(db, "ts_challenges"), where("status", "==", "scheduled"));
        const scheduledSnap = await getDocs(qScheduled);
        for (const docSnap of scheduledSnap.docs) {
            const data = docSnap.data();
            const startTime = parseISTDate(data.scheduledStartTime);
            if (!startTime || now >= startTime.getTime()) {
                await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                    status: "active",
                    activatedAt: serverTimestamp()
                });
                console.log(`⚡ [SYNC] Real-time activated: "${data.title}" (${docSnap.id})`);
            }
        }

        // 2. Close active -> closed if expired
        const qActive = query(collection(db, "ts_challenges"), where("status", "==", "active"));
        const activeSnap = await getDocs(qActive);
        for (const docSnap of activeSnap.docs) {
            const data = docSnap.data();
            if (data.scheduledEndTime) {
                const endTime = parseISTDate(data.scheduledEndTime);
                if (endTime && now >= endTime.getTime()) {
                    await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                        status: "closed",
                        closedAt: serverTimestamp()
                    });
                    console.log(`🔒 [SYNC] Real-time closed expired: "${data.title}" (${docSnap.id})`);
                }
            }
        }
    } catch (err) {
        // Silent error catch for recurring background sync
    }
}

// ═══════════════════════════════════════════════════════════
//  CRON SCHEDULES (IST Timezone: Asia/Kolkata)
// ═══════════════════════════════════════════════════════════

// 1. Friday 20:00 (8:00 PM IST)
cron.schedule("0 20 * * 5", () => {
    triggerFridayEveningSchedule();
}, { timezone: "Asia/Kolkata" });

// 2. Saturday 00:00 (Midnight IST)
cron.schedule("0 0 * * 6", () => {
    triggerSaturdayLiveActivation();
}, { timezone: "Asia/Kolkata" });

// 3. Sunday 23:59 (11:59 PM IST)
cron.schedule("59 23 * * 0", () => {
    triggerSundayClose();
}, { timezone: "Asia/Kolkata" });

// 4. Real-time Heartbeat (Every 1 minute)
cron.schedule("* * * * *", () => {
    checkRealtimeSync();
}, { timezone: "Asia/Kolkata" });

// ═══════════════════════════════════════════════════════════
//  HTTP SERVER (Port 8008)
// ═══════════════════════════════════════════════════════════

const server = http.createServer(async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        res.writeHead(204);
        res.end();
        return;
    }

    const reqUrl = new URL(req.url, `http://${req.headers.host}`);
    const pathname = reqUrl.pathname;
    const query = Object.fromEntries(reqUrl.searchParams);

    res.setHeader('Content-Type', 'application/json');

    try {
        // Health Check & Server Status
        if (pathname === '/' || pathname === '/health' || pathname === '/status') {
            res.writeHead(200);
            res.end(JSON.stringify({
                status: "online",
                service: "TechSpark Unified Backend & Scheduler Server",
                timezone: "Asia/Kolkata",
                currentTimeIST: new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }),
                rules: {
                    fridayAutoFetch: "Every Friday at 20:00 (8 PM IST)",
                    saturdayGoLive: "Every Saturday at 00:00 (Midnight IST)",
                    sundayAutoClose: "Every Sunday at 23:59 (11:59 PM IST)",
                    heartbeatSync: "Every 1 minute"
                },
                endpoints: [
                    "GET  /mcp/create-weekly-challenge?difficulty=EASY",
                    "GET  /mcp/fetch-leetcode-problem?difficulty=EASY",
                    "POST /mcp/generate-testcases",
                    "GET  /mcp/trigger-live-challenge?difficulty=EASY",
                    "GET  /mcp/trigger-friday-schedule",
                    "GET  /mcp/trigger-saturday-live",
                    "GET  /mcp/trigger-sunday-close"
                ]
            }, null, 2));
            return;
        }

        // Generate LeetCode Challenge with 10 Test Cases (Used by Admin Panel)
        if (pathname === '/mcp/create-weekly-challenge' && req.method === 'GET') {
            const difficulty = (query.difficulty || 'EASY').toUpperCase();
            const payload = await buildWeeklyChallengePayload(difficulty);
            if (!payload) {
                res.writeHead(500);
                res.end(JSON.stringify({ error: "Failed to generate challenge payload from LeetCode" }));
                return;
            }

            res.writeHead(200);
            res.end(JSON.stringify({
                success: true,
                message: "Weekly coding challenge generated for Saturday 00:00 to Sunday 23:59 (IST)",
                challenge: payload
            }));
            return;
        }

        // Fetch Raw LeetCode Problem
        if (pathname === '/mcp/fetch-leetcode-problem' && req.method === 'GET') {
            const difficulty = (query.difficulty || 'EASY').toUpperCase();
            const problem = await getRandomLeetCodeChallenge(difficulty);
            if (!problem) {
                res.writeHead(500);
                res.end(JSON.stringify({ error: "Failed to fetch problem from LeetCode" }));
                return;
            }

            const cleanDesc = cleanHtml(problem.content || "");
            res.writeHead(200);
            res.end(JSON.stringify({
                title: problem.title,
                titleSlug: problem.titleSlug,
                difficulty: problem.difficulty,
                problemStatement: cleanDesc,
                exampleTestcases: problem.exampleTestcases,
                codeSnippets: problem.codeSnippets || []
            }));
            return;
        }

        // Generate 10 Test Cases from Problem Content
        if (pathname === '/mcp/generate-testcases' && req.method === 'POST') {
            let body = '';
            req.on('data', chunk => { body += chunk.toString(); });
            req.on('end', () => {
                const data = JSON.parse(body || '{}');
                const { testcases } = generate10Testcases(
                    data.problem_title || 'Coding Challenge',
                    data.problem_content || '',
                    data.example_testcases || ''
                );
                res.writeHead(200);
                res.end(JSON.stringify({
                    title: data.problem_title,
                    totalTestCases: testcases.length,
                    testCases: testcases
                }));
            });
            return;
        }

        // Manual Trigger: Force Go Live Immediately
        if (pathname === '/mcp/trigger-live-challenge' && req.method === 'GET') {
            const result = await triggerSaturdayLiveActivation();
            res.writeHead(200);
            res.end(JSON.stringify({
                success: true,
                message: "Live challenge triggered and active in Firestore!",
                result
            }));
            return;
        }

        // Manual Trigger: Friday 8 PM Fetch & Schedule
        if (pathname === '/mcp/trigger-friday-schedule' && req.method === 'GET') {
            const result = await triggerFridayEveningSchedule();
            res.writeHead(200);
            res.end(JSON.stringify({
                success: true,
                message: "Friday evening schedule executed!",
                result
            }));
            return;
        }

        // Manual Trigger: Sunday Close
        if (pathname === '/mcp/trigger-sunday-close' && req.method === 'GET') {
            const result = await triggerSundayClose();
            res.writeHead(200);
            res.end(JSON.stringify({
                success: true,
                message: "Sunday close executed!",
                result
            }));
            return;
        }

        res.writeHead(404);
        res.end(JSON.stringify({ error: "Endpoint not found" }));

    } catch (err) {
        console.error("Server error:", err);
        res.writeHead(500);
        res.end(JSON.stringify({ error: err.message }));
    }
});

// Start Server
server.listen(PORT, () => {
    console.log("══════════════════════════════════════════════════════════════════════");
    console.log(`  🚀 TechSpark Unified Backend running at http://localhost:${PORT}`);
    console.log("  📅 Friday 20:00 IST (8 PM):   Auto-fetch & Schedule if missing");
    console.log("  ⚡ Saturday 00:00 (Midnight):  Auto-Go LIVE for students");
    console.log("  🔒 Sunday 23:59 (11:59 PM):   Auto-Close weekly challenge");
    console.log("  ⏱️ Real-time Heartbeat:       Every 1 minute (Asia/Kolkata)");
    console.log("  ⏰ Current IST Time:          " + new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }));
    console.log("══════════════════════════════════════════════════════════════════════");
});

// Run startup check immediately
checkRealtimeSync();
