import cron from "node-cron";
import { db, collection, addDoc, updateDoc, doc, query, where, getDocs, serverTimestamp } from "./firebaseBackend.js";
import { buildWeeklyChallengePayload } from "./automateChallenge.js";

/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  TechSpark Automated Weekly Coding Challenge Scheduler                   ║
 * ║  Timezone: Asia/Kolkata (IST - Indian Standard Time)                     ║
 * ║                                                                          ║
 * ║  1. Friday 20:00 IST (8 PM): Auto-fetch & schedule if not already posted ║
 * ║  2. Saturday 00:00 IST (Midnight): Go LIVE automatically                 ║
 * ║  3. Sunday 23:59 IST (Midnight): End & close challenge automatically     ║
 * ║  4. 1-Minute Continuous Cron: Ensures real-time IST state transitions    ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

/**
 * Safely parses any date representation into an IST-aware JS Date object.
 */
function parseISTDate(dateInput) {
    if (!dateInput) return null;
    if (typeof dateInput === 'object' && dateInput.toMillis) {
        return new Date(dateInput.toMillis());
    }
    if (typeof dateInput === 'number') {
        return new Date(dateInput);
    }
    if (typeof dateInput === 'string') {
        const str = dateInput.trim();
        if (str.includes('+') || str.endsWith('Z')) {
            return new Date(str);
        }
        if (/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}(:\d{2})?$/.test(str)) {
            return new Date(str.replace(' ', 'T') + '+05:30');
        }
        return new Date(str);
    }
    return new Date(dateInput);
}

/**
 * Checks if a valid active or scheduled challenge already exists for the upcoming weekend.
 */
async function getExistingWeekendChallenge() {
    try {
        const qScheduled = query(collection(db, "ts_challenges"), where("status", "==", "scheduled"));
        const qActive = query(collection(db, "ts_challenges"), where("status", "==", "active"));

        const [scheduledSnap, activeSnap] = await Promise.all([
            getDocs(qScheduled),
            getDocs(qActive)
        ]);

        if (!activeSnap.empty) {
            return activeSnap.docs[0];
        }
        if (!scheduledSnap.empty) {
            return scheduledSnap.docs[0];
        }
        return null;
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error checking existing challenges:", err.message);
        return null;
    }
}

/**
 * 1. Friday 20:00 (8:00 PM IST):
 * Checks if challenge is already prepared. If not, fetches from LeetCode and schedules it for Saturday 00:00 IST.
 */
async function prepareFridayEveningChallenge() {
    console.log("\n⏰ [AUTO-SCHEDULER] Friday 20:00 IST — Checking for weekend challenge...");

    try {
        const existing = await getExistingWeekendChallenge();
        if (existing) {
            console.log(`   ℹ️ Weekend challenge already exists: "${existing.data().title}" (${existing.id}) with status: ${existing.data().status}`);
            return;
        }

        console.log("   🚀 No challenge found. Auto-generating fresh LeetCode challenge...");
        const weekNumber = Math.ceil(new Date().getDate() / 7);
        const difficulty = weekNumber % 2 === 0 ? "MEDIUM" : "EASY";

        const payload = await buildWeeklyChallengePayload(difficulty);
        if (!payload) {
            console.error("❌ [AUTO-SCHEDULER] Failed to generate challenge payload.");
            return;
        }

        payload.status = "scheduled";

        const docRef = await addDoc(collection(db, "ts_challenges"), {
            ...payload,
            autoGenerated: true,
            createdAt: serverTimestamp()
        });

        console.log(`✅ [AUTO-SCHEDULER] Friday 20:00 IST — Successfully scheduled challenge for Saturday 00:00 IST!`);
        console.log(`   📝 Title: ${payload.title}`);
        console.log(`   🎯 Difficulty: ${payload.difficulty}`);
        console.log(`   🏆 XP: ${payload.xpPoints}`);
        console.log(`   ⏳ Scheduled Start: ${payload.scheduledStartTime}`);
        console.log(`   🆔 Firestore ID: ${docRef.id}`);
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error in Friday preparation:", err.message);
    }
}

/**
 * 2. Saturday 00:00 IST:
 * Activates the challenge so it becomes LIVE for students immediately.
 */
async function activateSaturdayChallenge() {
    console.log("\n⚡ [AUTO-SCHEDULER] Saturday 00:00 IST — Going LIVE...");

    try {
        const q = query(collection(db, "ts_challenges"), where("status", "==", "scheduled"));
        const snapshot = await getDocs(q);

        if (!snapshot.empty) {
            for (const docSnap of snapshot.docs) {
                await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                    status: "active",
                    activatedAt: serverTimestamp()
                });
                console.log(`   ⚡ [LIVE] Activated scheduled challenge: "${docSnap.data().title}" (${docSnap.id})`);
            }
            return;
        }

        // If nothing was scheduled, generate and activate immediately
        console.log("   🚀 No scheduled challenge found. Creating and activating new challenge now...");
        const weekNumber = Math.ceil(new Date().getDate() / 7);
        const difficulty = weekNumber % 2 === 0 ? "MEDIUM" : "EASY";

        const payload = await buildWeeklyChallengePayload(difficulty);
        if (payload) {
            payload.status = "active";
            const docRef = await addDoc(collection(db, "ts_challenges"), {
                ...payload,
                autoGenerated: true,
                createdAt: serverTimestamp()
            });
            console.log(`   ✅ [LIVE] Published and activated: "${payload.title}" (${docRef.id})`);
        }
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error in Saturday activation:", err.message);
    }
}

/**
 * 3. Sunday 23:59:59 IST:
 * Closes the active weekly coding challenge.
 */
async function closeSundayChallenge() {
    console.log("\n🔒 [AUTO-SCHEDULER] Sunday 23:59 IST — Ending & closing weekly challenge...");

    try {
        const q = query(
            collection(db, "ts_challenges"),
            where("status", "==", "active")
        );
        const snapshot = await getDocs(q);

        if (snapshot.empty) {
            console.log("   ℹ️ No active challenges to close.");
            return;
        }

        for (const docSnap of snapshot.docs) {
            await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                status: "closed",
                closedAt: serverTimestamp()
            });
            console.log(`   🔒 [CLOSED] Closed challenge: "${docSnap.data().title}" (${docSnap.id})`);
        }
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error closing Sunday challenge:", err.message);
    }
}

/**
 * 4. Real-time 1-Minute Cron Check in Asia/Kolkata:
 * - Promotes 'scheduled' challenges whose scheduledStartTime <= now to 'active'.
 * - Closes 'active' challenges whose scheduledEndTime <= now to 'closed'.
 */
async function checkRealtimeTransitions() {
    try {
        const now = Date.now();

        // 1. Check scheduled -> active
        const qScheduled = query(collection(db, "ts_challenges"), where("status", "==", "scheduled"));
        const scheduledSnap = await getDocs(qScheduled);

        for (const docSnap of scheduledSnap.docs) {
            const data = docSnap.data();
            const startTime = parseISTDate(data.scheduledStartTime);
            if (!startTime || now >= startTime.getTime()) {
                await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                    status: "active",
                    activatedAt: serverTimestamp()
                });
                console.log(`⚡ [AUTO-SCHEDULER] Real-time activated: "${data.title}" (${docSnap.id})`);
            }
        }

        // 2. Check active -> closed
        const qActive = query(collection(db, "ts_challenges"), where("status", "==", "active"));
        const activeSnap = await getDocs(qActive);

        for (const docSnap of activeSnap.docs) {
            const data = docSnap.data();
            if (data.scheduledEndTime) {
                const endTime = parseISTDate(data.scheduledEndTime);
                if (endTime && now >= endTime.getTime()) {
                    await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                        status: "closed",
                        closedAt: serverTimestamp()
                    });
                    console.log(`🔒 [AUTO-SCHEDULER] Real-time closed expired: "${data.title}" (${docSnap.id})`);
                }
            }
        }
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error in realtime check:", err.message);
    }
}

// ═══════════════════════════════════════════════════════════
//  CRON SCHEDULES (IST timezone: Asia/Kolkata)
// ═══════════════════════════════════════════════════════════

// 1. Every Friday at 20:00 (8:00 PM) IST
cron.schedule("0 20 * * 5", () => {
    prepareFridayEveningChallenge();
}, {
    timezone: "Asia/Kolkata"
});

// 2. Every Saturday at 00:00 (Midnight) IST
cron.schedule("0 0 * * 6", () => {
    activateSaturdayChallenge();
}, {
    timezone: "Asia/Kolkata"
});

// 3. Every Sunday at 23:59 (11:59 PM) IST
cron.schedule("59 23 * * 0", () => {
    closeSundayChallenge();
}, {
    timezone: "Asia/Kolkata"
});

// 4. Real-time transition check every 1 minute
cron.schedule("* * * * *", () => {
    checkRealtimeTransitions();
}, {
    timezone: "Asia/Kolkata"
});

// ═══════════════════════════════════════════════════════════

console.log("══════════════════════════════════════════════════════════════════");
console.log("  🤖 TechSpark Weekly Scheduler is ACTIVE (Asia/Kolkata / IST)");
console.log("  📅 Friday 20:00 (8 PM IST):  Auto-fetch & Schedule if missing");
console.log("  ⚡ Saturday 00:00 (Midnight): Auto-Go LIVE for students");
console.log("  🔒 Sunday 23:59 (11:59 PM):  Auto-Close weekly challenge");
console.log("  ⏱️ Real-time Heartbeat:      Every 1 minute");
console.log("  ⏰ Current IST Time:         " + new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }));
console.log("══════════════════════════════════════════════════════════════════");

// Immediate check on startup
checkRealtimeTransitions();

export {
    prepareFridayEveningChallenge,
    activateSaturdayChallenge,
    closeSundayChallenge,
    checkRealtimeTransitions
};
