import cron from "node-cron";
import { db, collection, addDoc, updateDoc, doc, query, where, getDocs, serverTimestamp } from "./firebaseBackend.js";
import { buildWeeklyChallengePayload } from "./automateChallenge.js";

/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║  TechSpark Weekly Coding Challenge Auto-Scheduler       ║
 * ║  Schedule: Saturday 00:00 (IST) → Sunday 24:00 (IST)   ║
 * ║  No manual button press needed!                         ║
 * ╚══════════════════════════════════════════════════════════╝
 */

// Track the current active challenge ID for auto-closing
let currentChallengeId = null;

/**
 * Publishes a new LeetCode challenge to Firestore with status "active".
 */
async function publishWeeklyChallenge() {
    console.log("\n🚀 [AUTO-SCHEDULER] Saturday 00:00 — Fetching LeetCode challenge...");

    try {
        // Alternate Easy/Medium each week
        const weekNumber = Math.ceil((new Date().getDate()) / 7);
        const difficulty = weekNumber % 2 === 0 ? "MEDIUM" : "EASY";

        const payload = await buildWeeklyChallengePayload(difficulty);
        if (!payload) {
            console.error("❌ [AUTO-SCHEDULER] Failed to generate challenge payload.");
            return;
        }

        // Override status to active (live immediately)
        payload.status = "active";

        const docRef = await addDoc(collection(db, "ts_challenges"), {
            ...payload,
            autoGenerated: true,
            createdAt: serverTimestamp(),
        });

        currentChallengeId = docRef.id;

        console.log(`✅ [AUTO-SCHEDULER] Challenge published to Firestore!`);
        console.log(`   📝 Title: ${payload.title}`);
        console.log(`   🎯 Difficulty: ${payload.difficulty}`);
        console.log(`   🏆 XP: ${payload.xpPoints}`);
        console.log(`   🧪 Test Cases: ${payload.testCasesCount}`);
        console.log(`   🔥 Status: ACTIVE`);
        console.log(`   🆔 Firestore ID: ${docRef.id}`);
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error publishing challenge:", err.message);
    }
}

/**
 * Auto-closes the current challenge by setting status to "closed".
 */
async function closeWeeklyChallenge() {
    console.log("\n🔒 [AUTO-SCHEDULER] Sunday 24:00 — Closing active challenges...");

    try {
        // Close ALL active auto-generated challenges
        const q = query(
            collection(db, "ts_challenges"),
            where("status", "==", "active"),
            where("autoGenerated", "==", true)
        );
        const snapshot = await getDocs(q);

        if (snapshot.empty) {
            console.log("   ℹ️ No active auto-generated challenges to close.");
            return;
        }

        for (const docSnap of snapshot.docs) {
            await updateDoc(doc(db, "ts_challenges", docSnap.id), {
                status: "closed",
            });
            console.log(`   ✅ Closed challenge: ${docSnap.data().title} (${docSnap.id})`);
        }

        currentChallengeId = null;
        console.log("🔒 [AUTO-SCHEDULER] All weekly challenges closed successfully.");
    } catch (err) {
        console.error("❌ [AUTO-SCHEDULER] Error closing challenges:", err.message);
    }
}

// ═══════════════════════════════════════════════════════════
//  CRON SCHEDULES (IST timezone)
// ═══════════════════════════════════════════════════════════

// ⏰ Every Saturday at 00:00 IST → Publish new LeetCode challenge
cron.schedule("0 0 * * 6", () => {
    console.log("⏰ [CRON] Saturday 00:00 IST triggered!");
    publishWeeklyChallenge();
}, {
    timezone: "Asia/Kolkata"
});

// ⏰ Every Monday at 00:00 IST (= Sunday 24:00) → Close the challenge
cron.schedule("0 0 * * 1", () => {
    console.log("⏰ [CRON] Monday 00:00 IST (Sunday 24:00) triggered!");
    closeWeeklyChallenge();
}, {
    timezone: "Asia/Kolkata"
});

// ═══════════════════════════════════════════════════════════

console.log("═══════════════════════════════════════════════════");
console.log("  🤖 TechSpark Auto-Scheduler is RUNNING");
console.log("  📅 Publish: Every Saturday at 00:00 IST");
console.log("  🔒 Close:   Every Monday at 00:00 IST (Sunday 24:00)");
console.log("  🔄 Difficulty: Alternates Easy ↔ Medium each week");
console.log("  ⏰ Current Time: " + new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }));
console.log("═══════════════════════════════════════════════════");

// Export for testing
export { publishWeeklyChallenge, closeWeeklyChallenge };
